# Generated by Django 2.2.1 on 2019-10-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191006_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='products.OrderItem'),
        ),
    ]
