# Generated by Django 2.2.1 on 2019-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_html',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('I', 'Indian'), ('CH', 'Chinese'), ('CN', 'Continental'), ('BV', 'Beverages')], max_length=20),
        ),
    ]
